// Lesson tests: do not edit this file. Change only src/main.rs.

// This is an integration test: it runs the compiled binary as a separate process,
// the same way you would run it from a terminal.
use std::process::{Command, Output};

fn run_program() -> Output {
    // Cargo builds the binary before running integration tests and passes its path
    // in the CARGO_BIN_EXE_<name> environment variable at compile time.
    Command::new(env!("CARGO_BIN_EXE_lesson-000-hello-world"))
        .output()
        .expect("failed to run the lesson binary")
}

#[test]
fn prints_hello_world_to_stdout() {
    let output = run_program();
    let stdout = String::from_utf8_lossy(&output.stdout);

    assert_eq!(stdout, "Hello, world!\n");
}

#[test]
fn exits_successfully_and_keeps_stderr_empty() {
    let output = run_program();
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert!(
        output.status.success(),
        "the program must exit with code 0, got {}",
        output.status
    );
    assert_eq!(stderr, "", "the program must not write to stderr");
}
